const supportedLanguages = ['en', 'hi', 'as', 'bn'];

const languageNames = {
  'en': 'English',
  'hi': 'हिन्दी',
  'as': 'অসমীয়া',
  'bn': 'বাংলা',
};

const Map<String, Map<String, String>> _strings = {
  'en': {
    'nav_report': 'Report',
    'nav_alerts': 'Alerts',
    'report_appbar': 'Report a hazard',
    'alerts_appbar': 'Alerts',
    'language': 'Language',
    'district_label': 'District',
    'description_label': 'What did you observe?',
    'capture_location': 'Capture current location',
    'location_prefix': 'Location',
    'photo': 'Photo',
    'gallery': 'Gallery',
    'video': 'Video',
    'attached': 'Attached',
    'submit': 'Submit report',
    'submitting': 'Submitting…',
    'sync': 'Sync saved reports',
    'ready': 'Ready',
    'describe_min': 'Describe the hazard in at least 3 characters.',
    'getting_location': 'Getting current location...',
    'location_denied': 'Location permission denied — using default coordinates.',
    'location_off': 'Location services are off — using default coordinates.',
    'location_captured': 'Location captured',
    'location_failed': 'Could not get location — using default coordinates.',
    'media_attached': 'Media attached',
    'upload_failed': 'Could not upload media (offline?) — submitting report without it.',
    'report_sent': 'Report sent.',
    'report_offline': 'Offline: report saved and will sync later.',
    'sync_finished': 'Sync finished.',
    'still_queued': 'report(s) still queued.',
    'no_alerts': 'No alerts yet.',
    'alerts_load_error': 'Could not load alerts.',
    'alerts_offline': 'Offline — could not reach the server.',
    'loading': 'Loading...',
    'unknown_location': 'Unknown location',
    'crack': 'Crack', 'slope_movement': 'Slope movement', 'landslide': 'Landslide',
    'blocked_road': 'Blocked road', 'rockfall': 'Rockfall', 'flooding': 'Flooding',
    'low': 'Low', 'moderate': 'Moderate', 'high': 'High', 'critical': 'Critical',
  },
  'hi': {
    'nav_report': 'रिपोर्ट',
    'nav_alerts': 'चेतावनी',
    'report_appbar': 'खतरे की रिपोर्ट करें',
    'alerts_appbar': 'चेतावनियाँ',
    'language': 'भाषा',
    'district_label': 'जिला',
    'description_label': 'आपने क्या देखा?',
    'capture_location': 'वर्तमान स्थान प्राप्त करें',
    'location_prefix': 'स्थान',
    'photo': 'फ़ोटो',
    'gallery': 'गैलरी',
    'video': 'वीडियो',
    'attached': 'संलग्न',
    'submit': 'रिपोर्ट भेजें',
    'submitting': 'भेजा जा रहा है…',
    'sync': 'सहेजी गई रिपोर्ट सिंक करें',
    'ready': 'तैयार',
    'describe_min': 'कृपया कम से कम 3 अक्षरों में खतरे का वर्णन करें।',
    'getting_location': 'वर्तमान स्थान प्राप्त किया जा रहा है...',
    'location_denied': 'स्थान की अनुमति अस्वीकृत — डिफ़ॉल्ट निर्देशांक उपयोग हो रहे हैं।',
    'location_off': 'स्थान सेवाएँ बंद हैं — डिफ़ॉल्ट निर्देशांक उपयोग हो रहे हैं।',
    'location_captured': 'स्थान प्राप्त हुआ',
    'location_failed': 'स्थान प्राप्त नहीं हो सका — डिफ़ॉल्ट निर्देशांक उपयोग हो रहे हैं।',
    'media_attached': 'मीडिया संलग्न किया गया',
    'upload_failed': 'मीडिया अपलोड नहीं हो सका (ऑफ़लाइन?) — बिना मीडिया के रिपोर्ट भेजी जा रही है।',
    'report_sent': 'रिपोर्ट भेज दी गई।',
    'report_offline': 'ऑफ़लाइन: रिपोर्ट सहेजी गई है और बाद में भेजी जाएगी।',
    'sync_finished': 'सिंक पूर्ण हुआ।',
    'still_queued': 'रिपोर्ट(एँ) अभी भी लंबित हैं।',
    'no_alerts': 'अभी कोई चेतावनी नहीं है।',
    'alerts_load_error': 'चेतावनियाँ लोड नहीं हो सकीं।',
    'alerts_offline': 'ऑफ़लाइन — सर्वर से संपर्क नहीं हो सका।',
    'loading': 'लोड हो रहा है...',
    'unknown_location': 'अज्ञात स्थान',
    'crack': 'दरार', 'slope_movement': 'ढलान खिसकना', 'landslide': 'भूस्खलन',
    'blocked_road': 'अवरुद्ध सड़क', 'rockfall': 'चट्टान गिरना', 'flooding': 'बाढ़',
    'low': 'निम्न', 'moderate': 'मध्यम', 'high': 'उच्च', 'critical': 'अति गंभीर',
  },
  'as': {
    'nav_report': 'প্ৰতিবেদন',
    'nav_alerts': 'সতৰ্কবাণী',
    'report_appbar': 'বিপদৰ প্ৰতিবেদন কৰক',
    'alerts_appbar': 'সতৰ্কবাণীসমূহ',
    'language': 'ভাষা',
    'district_label': 'জিলা',
    'description_label': 'আপুনি কি দেখিলে?',
    'capture_location': 'বৰ্তমান অৱস্থান লওক',
    'location_prefix': 'অৱস্থান',
    'photo': 'ফটো',
    'gallery': "গেলাৰী",
    'video': "ভিডিঅ'",
    'attached': 'সংলগ্ন কৰা হৈছে',
    'submit': 'প্ৰতিবেদন পঠিয়াওক',
    'submitting': 'পঠিওৱা হৈছে…',
    'sync': 'সংৰক্ষিত প্ৰতিবেদন ছিংক কৰক',
    'ready': 'প্ৰস্তুত',
    'describe_min': 'অনুগ্ৰহ কৰি অতি কমেও ৩টা আখৰেৰে বিপদৰ বিৱৰণ দিয়ক।',
    'getting_location': 'বৰ্তমান অৱস্থান লোৱা হৈছে...',
    'location_denied': 'অৱস্থানৰ অনুমতি নাকচ কৰা হৈছে — অবিকল্পিত স্থানাংক ব্যৱহাৰ কৰা হৈছে।',
    'location_off': 'অৱস্থান সেৱা বন্ধ আছে — অবিকল্পিত স্থানাংক ব্যৱহাৰ কৰা হৈছে।',
    'location_captured': "অৱস্থান পোৱা গ'ল",
    'location_failed': "অৱস্থান পোৱা নগ'ল — অবিকল্পিত স্থানাংক ব্যৱহাৰ কৰা হৈছে।",
    'media_attached': "মিডিয়া সংলগ্ন কৰা হ'ল",
    'upload_failed': "মিডিয়া আপল'ড কৰিব পৰা নগ'ল (অফলাইন?) — মিডিয়া অবিহনে প্ৰতিবেদন পঠোৱা হৈছে।",
    'report_sent': "প্ৰতিবেদন পঠোৱা হ'ল।",
    'report_offline': "অফলাইন: প্ৰতিবেদন সংৰক্ষিত হ'ল আৰু পিছত পঠোৱা হ'ব।",
    'sync_finished': "ছিংক সম্পূৰ্ণ হ'ল।",
    'still_queued': 'টা প্ৰতিবেদন এতিয়াও বাকী আছে।',
    'no_alerts': 'এতিয়ালৈকে কোনো সতৰ্কবাণী নাই।',
    'alerts_load_error': "সতৰ্কবাণী ল'ড কৰিব পৰা নগ'ল।",
    'alerts_offline': "অফলাইন — চাৰ্ভাৰৰ সৈতে সংযোগ কৰিব পৰা নগ'ল।",
    'loading': "ল'ড হৈ আছে...",
    'unknown_location': 'অজ্ঞাত স্থান',
    'crack': 'ফাট', 'slope_movement': 'ঢাল স্থানান্তৰ', 'landslide': 'ভূমিস্খলন',
    'blocked_road': 'বন্ধ ৰাস্তা', 'rockfall': 'শিল খহন', 'flooding': 'বান',
    'low': 'নিম্ন', 'moderate': 'মধ্যম', 'high': 'উচ্চ', 'critical': 'গুৰুতৰ',
  },
  'bn': {
    'nav_report': 'প্রতিবেদন',
    'nav_alerts': 'সতর্কতা',
    'report_appbar': 'বিপদের প্রতিবেদন করুন',
    'alerts_appbar': 'সতর্কতাসমূহ',
    'language': 'ভাষা',
    'district_label': 'জেলা',
    'description_label': 'আপনি কী দেখেছেন?',
    'capture_location': 'বর্তমান অবস্থান নিন',
    'location_prefix': 'অবস্থান',
    'photo': 'ছবি',
    'gallery': 'গ্যালারি',
    'video': 'ভিডিও',
    'attached': 'সংযুক্ত',
    'submit': 'প্রতিবেদন পাঠান',
    'submitting': 'পাঠানো হচ্ছে…',
    'sync': 'সংরক্ষিত প্রতিবেদন সিঙ্ক করুন',
    'ready': 'প্রস্তুত',
    'describe_min': 'অনুগ্রহ করে অন্তত ৩টি অক্ষরে বিপদের বর্ণনা দিন।',
    'getting_location': 'বর্তমান অবস্থান নেওয়া হচ্ছে...',
    'location_denied': 'অবস্থানের অনুমতি প্রত্যাখ্যান করা হয়েছে — ডিফল্ট স্থানাঙ্ক ব্যবহার করা হচ্ছে।',
    'location_off': 'অবস্থান পরিষেবা বন্ধ আছে — ডিফল্ট স্থানাঙ্ক ব্যবহার করা হচ্ছে।',
    'location_captured': 'অবস্থান পাওয়া গেছে',
    'location_failed': 'অবস্থান পাওয়া যায়নি — ডিফল্ট স্থানাঙ্ক ব্যবহার করা হচ্ছে।',
    'media_attached': 'মিডিয়া সংযুক্ত করা হয়েছে',
    'upload_failed': 'মিডিয়া আপলোড করা যায়নি (অফলাইন?) — মিডিয়া ছাড়াই প্রতিবেদন পাঠানো হচ্ছে।',
    'report_sent': 'প্রতিবেদন পাঠানো হয়েছে।',
    'report_offline': 'অফলাইন: প্রতিবেদন সংরক্ষিত হয়েছে এবং পরে পাঠানো হবে।',
    'sync_finished': 'সিঙ্ক সম্পন্ন হয়েছে।',
    'still_queued': 'টি প্রতিবেদন এখনও অপেক্ষমাণ।',
    'no_alerts': 'এখনও কোনো সতর্কতা নেই।',
    'alerts_load_error': 'সতর্কতা লোড করা যায়নি।',
    'alerts_offline': 'অফলাইন — সার্ভারের সাথে যোগাযোগ করা যায়নি।',
    'loading': 'লোড হচ্ছে...',
    'unknown_location': 'অজানা স্থান',
    'crack': 'ফাটল', 'slope_movement': 'ঢাল সরণ', 'landslide': 'ভূমিধস',
    'blocked_road': 'বন্ধ রাস্তা', 'rockfall': 'পাথর ধস', 'flooding': 'বন্যা',
    'low': 'নিম্ন', 'moderate': 'মাঝারি', 'high': 'উচ্চ', 'critical': 'সংকটজনক',
  },
};

String t(String lang, String key) => _strings[lang]?[key] ?? _strings['en']![key] ?? key;
